apiVersion: v1
kind: Service
metadata:
  name: emp-springboot-service
spec: 
  selector:
    app: emp-springboot-app
  ports: 
    - protocol: TCP
      port: 8080
      targetPort: 8088
      nodePort: 31005
  type: NodePort

