apiVersion: v1
kind: Service
metadata: 
  name: emp-mysql-service
spec: 
  selector:
    app: emp-mysql-app
  ports: 
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 31004
  type: NodePort
